    spring:
      application:
        name: SpringDataJPA
      datasource:
        url: jdbc:postgresql://127.0.0.1:5432/testing
        username: postgres
        password: qwerty
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
    springdoc:
      swagger-ui:
        path: /api

    file_storage:
      image_location: "filestorage/images/"
      database_location: "filestorage/data/"